### ISSUE TITLE
Capacity tests need to be refactored

### ISSUE THREAD

**Issue by john-kheir** [threefoldtech/jumpscaleX_libs_extra#2]
All the capacity tests [here](https://github.com/threefoldtech/jumpscaleX_libs_extra/blob/master/JumpscaleLibsExtra/tools/capacity/test_parser.py) need to be refactored

**Comment by zaibon** [comment]
This module can actually be deleted. This logic is now located in 0-OS itself.

**Comment by gmachtel** [comment]
Closed given zaibon comment

**Comment by john-kheir** [comment]
https://github.com/threefoldtech/jumpscaleX_libs_extra/commit/a3241c32217bfeee91d8c03f3852dd1104c71878
