### ISSUE TITLE
Error while calling j.tools.reportlab2  

### ISSUE THREAD

**Issue by john-kheir** [threefoldtech/jumpscaleX_libs_extra#22]
## branch 
development
## Error
```
JSX> j.tools.reportlab2                                                                            
Mon 16 10:25:13 /reportlab2/RLDoc.py -   1 - <module>                           : EXCEPTION: 
    ModuleNotFoundError("No module named 'reportlab'",)
--TRACEBACK------------------
<stdin> in <module>
    1    
/sandbox/lib/jumpscale/jumpscale_generated.py in reportlab2
    376    from JumpscaleLibsExtra.tools.reportlab2.ReportlabFactory import ReportlabFactory
/sandbox/lib/jumpscale/JumpscaleLibsExtra/tools/reportlab2/ReportlabFactory.py in <module>
    2    from .RLDoc import RLDoc
/sandbox/lib/jumpscale/JumpscaleLibsExtra/tools/reportlab2/RLDoc.py in <module>
    1    from reportlab.lib.pagesizes import A4
-----------------------------

No module named 'reportlab'

```

**Comment by m-motawea** [comment]
Fixed in commit https://github.com/threefoldtech/jumpscaleX_libs_extra/commit/96557139f81c276bea68b2eabf158ae69451321b branch unstable

**Comment by hossnys** [comment]
verified on branch unstable 
![Screenshot from 2020-03-18 22-03-07](https://user-images.githubusercontent.com/26298009/77042180-e7664580-69c3-11ea-8887-e9e416217d74.png)

![Screenshot from 2020-03-18 22-07-27](https://user-images.githubusercontent.com/26298009/77042141-da495680-69c3-11ea-80c0-11524242b892.png)

**Comment by Dina-Abd-Elrahman** [comment]
- I got an error in test method 

![ff](https://user-images.githubusercontent.com/21218053/77043330-fcdc6f00-69c5-11ea-8ce5-d9d8daf0f0ef.png)



![ff](https://user-images.githubusercontent.com/21218053/77043492-4f1d9000-69c6-11ea-9bda-a7e4af363b22.png)

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
